# Generated by Django 2.1 on 2018-08-29 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('acronym', models.CharField(max_length=100)),
                ('topics', models.CharField(max_length=100)),
                ('start_date', models.CharField(max_length=100)),
                ('deadline_date', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
