# Generated by Django 2.1 on 2018-09-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='favoritos',
            field=models.BooleanField(default=False),
        ),
    ]
